# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Capacitor"
description: > # this means to ignore newlines until "email:"
   Simple device capacity

email: a-mail@mail.mail
#blog logo
logo: "/Storage-Capacitor/assets/images/cap_logo.png"
# blog cover
#cover: "/Storage-Capacitor/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Kelly Plummer'
author: 'Kelly Plummer'
author_image: "/Storage-Capacitor/assets/images/author.jpg"

paginate:	5

url: "http://kellyp.github.io/Storage-Capacitor" # the base hostname & protocol for your site
baseurl: "/Storage-Capacitor"

itunes:
  url: http://itunesurl
# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/kellyplummer
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/kellyp
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
